apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eureka-app
  template:
    metadata:
      labels:
        app: eureka-app
    spec:
      containers:
      - name: eureka-app
        image: us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-app-service
spec:
  selector:
    app: eureka-app
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
